# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.puppet_install.puppet_version = :latest

  config.vm.provider "virtualbox" do |vb|
    config.vm.box = "bento/ubuntu-18.04"
    vb.memory = 512
    vb.cpus = 1
  end

  config.vm.provider :digital_ocean do |provider, override|
    override.ssh.private_key_path = '~/.ssh/id_rsa'
    override.vm.allowed_synced_folder_types = :rsync
    override.vm.box = 'digital_ocean'
    override.vm.box_url = "https://github.com/devopsgroup-io/vagrant-digitalocean/raw/master/box/digital_ocean.box"

    provider.token = ENV['DIGITALOCEAN_TOKEN']
    provider.image = 'ubuntu-18-04-x64'
    provider.region = 'nyc1'
    provider.size = 's-1vcpu-1gb'
    provider.setup = false
  end

  
  config.vm.define "appserver" do |app|
    app.vm.hostname = "appserver"
  end
  config.vm.define "dbserver" do |db|
    db.vm.hostname = "dbserver"
  end

  config.vm.provision "puppet"
end
