# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.provider "virtualbox" do |vb|
    config.vm.box = "bento/ubuntu-18.04"
    vb.memory = 512
    vb.cpus = 1
  end

  config.vm.define "app" do |app|
    app.vm.hostname = "appserver"
    app.vm.network "private_network", ip: "192.168.56.4"
  end
  config.vm.define "db" do |db|
    db.vm.hostname = "dbserver"
    db.vm.network "private_network", ip: "192.168.56.5"
  end
  config.vm.define "web" do |web|
    web.vm.hostname = "web"
    web.vm.network "private_network", ip: "192.168.56.6"
  end
  
  config.vm.define "tst0" do |tst0|
    tst0.vm.hostname = "tst0"
    tst0.vm.network "private_network", ip: "192.168.56.7"
  end
  config.vm.define "tst1" do |tst1|
    tst1.vm.hostname = "tst1"
    tst1.vm.network "private_network", ip: "192.168.56.8"
  end
  config.vm.define "tst2" do |tst2|
    tst2.vm.hostname = "tst2"
    tst2.vm.network "private_network", ip: "192.168.56.9"
  end

  # config.vm.provision "shell", inline: <<-SHELL
  #   dpkg -i /vagrant/pkg/puppet-release-jammy.deb
  #   apt-get -qq update
  #   apt-get install -y puppet-agent
  # SHELL

  config.vm.provision "puppet"
end
